// <auto-generated />
using System;
using ComputerStore.Services.CS.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("92e03aa9-ab82-47bc-ab26-dc6bd5dffd68"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "8GB 128-Bit GDDR6",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 1357m,
                            Title = "PELADN AMD Radeon RX6650XT 8GB GDDR6 PCI Express 4.0 Video Card",
                            Type = 5
                        },
                        new
                        {
                            Id = new Guid("4f70c07a-0f46-481f-a037-4c73b766b16f"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Intel 7 Alder Lake Processor Base Power: 65W Maximum Turbo Power: 117W 18MB L3 Cache 7.5MB L2 Cache Windows 11 Supported Intel Laminar RM1 CPU Cooler",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 50.00m,
                            Title = "Intel Core i5-12400F",
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("8d9d8ab8-82c6-452f-b804-ecccb7f43163"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Intel LGA 1700 socket: Ready for 13th Gen Intel Core, and 12th Gen Intel Core, Pentium Gold, and Celeron® processors.",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 137.73m,
                            Title = "ASUS ROG STRIX Z790-H Gaming",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("249c7e5c-caa7-4786-8865-7558cf439cbc"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "7200 RPM 256MB Cache SATA 6.0Gb For Enterprise Storage",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 141.98m,
                            Title = "Seagate Exos X20 ST20000NM007D ",
                            Type = 4
                        },
                        new
                        {
                            Id = new Guid("af6b1042-e017-4b60-963e-58001220ebf6"),
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "NVMe M.2 PCIe Gen4 x4 Interface. PCIe 4.0 Compliant / NVMe 1.3 Compliant.\r\nPower Management Support for APST / ASPM / L1.2.",
                            ModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 417.14m,
                            Title = "SABRENT 500GB Rocket Nvme PCIe 4.0 M.2 2280",
                            Type = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
